In [14]:
"""
@filename: ttest
@dataset: ttest
@author: waisullah yousofi
"""

'\n@filename: ttest\n@dataset: ttest\n@author: waisullah yousofi\n'

hides all warnings

In [15]:
import warnings
warnings.filterwarnings('ignore')
# pandas 
import pandas as pd
# numpy
import numpy as np
# stats
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html
from scipy.stats import ttest_rel

############################################################<br>
Read Data <br>
############################################################

assign spreadsheet filename: file

In [16]:
file = '..\dataset/ttest-data.xlsx'

load spreadsheet xls

In [17]:
xls = pd.ExcelFile(file)

print sheet names

In [18]:
print(xls.sheet_names)

['tTest-1SMwoSD-1', 'tTest-1SMwoSD-2', 'tTest-Ind2SM-1', 'tTest-Ind2SM-2', 'tTest-Dep2SM-1', 'tTest-Dep2SM-2', 'Chi-Sq-GoF-1', 'Chi-Sq-GoF-2', 'Chi-Sq-ToI-1', 'Chi-Sq-ToI-2', 'Anova-1Factor-1', 'Anova-1Factor-2', 'Anova-1Factor-P1']


load a sheet into a dataFrame by name

In [21]:
df = xls.parse('tTest-Dep2SM-1')
df

Product  Pune  Mumbai
0       A   710     790
1       B   900    1010
2       C  1100    1220
3       D   890     880
4       E   990    1040
5       F   910     900
6       G  1030    1170
7       H   800     820
8       I   900     990
9       J   600     650

print df

In [22]:
colNames = df.columns.tolist()
for colName in colNames:
    print(df[colName].values.flatten())

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
[ 710  900 1100  890  990  910 1030  800  900  600]
[ 790 1010 1220  880 1040  900 1170  820  990  650]


############################################################<br>
Hypothesis Test<br>
############################################################

Problem	Prices of given products in two given cities is same				

 0.05<br>
-mu - m-pu = 0<br>
-mu - m-pu != 0<br>
woTailed<br>
est: Dep Two Sample Mean

null hyp

In [23]:
Ho = "m-mu - m-pu = 0"
# alt hyp
Ha = "m-mu - m-pu != 0"
# alpha
al = 0.05
# tail type
tt = 2
# data
d_mu = df['Mumbai'].values
d_pu = df['Pune'].values
d_mu = d_mu[~np.isnan(d_mu)]
d_pu = d_pu[~np.isnan(d_pu)]

print

In [24]:
print("Ho:", Ho)
print("Ha:", Ha)
print("al:", al)
#print("mu:", mu)
print()
print(d_mu)
print(d_pu)
print("")

Ho: m-mu - m-pu = 0
Ha: m-mu - m-pu != 0
al: 0.05

[ 790 1010 1220  880 1040  900 1170  820  990  650]
[ 710  900 1100  890  990  910 1030  800  900  600]



In [25]:
ts, pv = ttest_rel(d_mu, d_pu)
print("t-stat",ts)
print("p-vals",pv)
t2pv = pv
t1pv = pv*2
print("1t pv",t1pv)
print("2t pv",t2pv)

t-stat 3.821699657558558
p-vals 0.004079274360829899
1t pv 0.008158548721659798
2t pv 0.004079274360829899


In [26]:
if tt == 1:
    if t1pv < al:
        print("Null Hypothesis: Rejected")
        print("Conclusion:",Ha)
    else:
        print("Null Hypothesis: Not Rejected")
        print("Conclusion:",Ho)
else:
    if t2pv < al/2:
        print("Null Hypothesis: Rejected")
        print("Conclusion:",Ha)
    else:
        print("Null Hypothesis: Not Rejected")
        print("Conclusion:",Ho)

Null Hypothesis: Rejected
Conclusion: m-mu - m-pu != 0


############################################################

Problem	Prices of given products in two given cities is same				

 0.05<br>
-mu - m-nm = 0<br>
-mu - m-nm <> 0<br>
woTailed<br>
est: Dep Two Sample Mean

null hyp

In [37]:
Ho = "m-mu - m-nm = 0"
# alt hyp
Ha = "m-mu - m-nm != 0"
# alpha
al = 0.05
# mu - mean
#mu = 66
# tail type
tt = 2
# data
d_mu = df['Mumbai'].values
d_nm = df['Mumbai'].values
d_mu = d_mu[~np.isnan(d_mu)]
d_nm = d_nm[~np.isnan(d_nm)]
# print
print("Ho:", Ho)
print("Ha:", Ha)
print("al:", al)
#print("mu:", mu)
print()
print(d_mu)
print(d_nm)
print("")

Ho: m-mu - m-nm = 0
Ha: m-mu - m-nm != 0
al: 0.05

[ 790 1010 1220  880 1040  900 1170  820  990  650]
[ 790 1010 1220  880 1040  900 1170  820  990  650]



In [38]:
ts, pv = ttest_rel(d_mu, d_nm)
print("t-stat",ts)
print("p-vals",pv)
t2pv = pv
t1pv = pv*2
print("1t pv",t1pv)
print("2t pv",t2pv)

t-stat nan
p-vals nan
1t pv nan
2t pv nan
