In [1]:
"""
@filename: ttest
@dataset: ttest
@author: waisullah yousofi
"""

'\n@filename: ttest\n@dataset: ttest\n@author: waisullah yousofi\n'

hides all warnings

In [2]:
import warnings
warnings.filterwarnings('ignore')
# pandas 
import pandas as pd
# numpy
import numpy as np
# stats
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html
from scipy.stats import f_oneway

############################################################<br>
Read Data <br>
############################################################

assign spreadsheet filename: file

In [3]:
file = '..\dataset/ttest-data.xlsx'

load spreadsheet xls

In [4]:
xls = pd.ExcelFile(file)

print sheet names

In [5]:
print(xls.sheet_names)

['tTest-1SMwoSD-1', 'tTest-1SMwoSD-2', 'tTest-Ind2SM-1', 'tTest-Ind2SM-2', 'tTest-Dep2SM-1', 'tTest-Dep2SM-2', 'Chi-Sq-GoF-1', 'Chi-Sq-GoF-2', 'Chi-Sq-ToI-1', 'Chi-Sq-ToI-2', 'Anova-1Factor-1', 'Anova-1Factor-2', 'Anova-1Factor-P1']


load a sheet into a dataFrame by name

In [6]:
df = xls.parse('Anova-1Factor-2')

print df

In [7]:
colNames = df.columns.tolist()
for colName in colNames:
    print(df[colName].values.flatten())

[60. 60. 62. 61. 62. 63. 57. 60. nan]
[69. 64. 58. 64. 64. 65. 66. nan nan]
[54 55 55 53 60 61 59 58 62]


############################################################<br>
ANOVA Test<br>
############################################################

Title Chi-Square Godness Of Fit	<br>
Problem	Mean of the marks obtained students (not same) of three subjects are same / similar

alpha	0.05<br>
Ho	μ1 = μ2 = μ3<br>
Ha	at least one of the means is different<br>
Test	Annova: Single Factor

null hyp

In [8]:
Ho = "μ1 = μ2 = μ3"
# alt hyp
Ha = "at least one of the means is different"
# alpha
al = 0.05

print

In [9]:
print("Ho:", Ho)
print("Ha:", Ha)
print("al:", al)
# data
colNames = df.columns.tolist()
data = []
for i, colName in enumerate(colNames):
    #print(i)
    print(colName)
    colVals = df[colName].values.flatten()
    colVals = colVals[~np.isnan(colVals)]
    data.append(colVals)
    print(colVals)  
    print(colVals.mean())          
print("")
rs=f_oneway(data[0],data[1],data[2])
av = rs[0]
pv = rs[1]
print("result",rs)
print("a-stat",av)
print("p-vals",pv)

Ho: μ1 = μ2 = μ3
Ha: at least one of the means is different
al: 0.05
Economics
[60. 60. 62. 61. 62. 63. 57. 60.]
60.625
Maths
[69. 64. 58. 64. 64. 65. 66.]
64.28571428571429
Stats
[54 55 55 53 60 61 59 58 62]
57.44444444444444

result F_onewayResult(statistic=11.035296444921718, pvalue=0.0005301559850885425)
a-stat 11.035296444921718
p-vals 0.0005301559850885425
